<div id="breadcrumbs" class="breadcrumbs"><?php echo $breadcrumbs;?></div>
<div id="content-header" class="content-header">
	<button id="btn-crog" class="btn btn-primary btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'crog'?>" data-message="">
		<span>查看配置</span>
	</button>
	<button id="btn-list" class="btn btn-info btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'index'?>"
		data-message="">
		<span>数据概览</span>
	</button>
	<button id="btn-adds" class="btn btn-info btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'adds'?>" data-message="">
		<span>添加记录</span>
	</button>
	<button id="btn-back" class="btn btn-default btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'index'?>"
		data-message="">
		<span>返回上层</span>
	</button>
	<button id="btn-save" class="btn btn-success btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'save'?>" data-message="">
		<span>保存数据</span>
	</button>
	<button id="btn-warning" class="btn btn-warning btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'warning'?>"
		data-message="你确定要进行此操作吗？">
		<span>警告按钮</span>
	</button>
	<button id="btn-delete" class="btn btn-danger btn-lg btn-customize "
		data-url="<?php echo  DS . $controller. DS . 'delete'?>"
		data-message="你确定要删除当前记录吗？">
		<span>删除记录</span>
	</button>
</div>
