<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Tutorial\Module'                        => __DIR__ . '/Module.php',
    'Tutorial\Controller\T1Controller' => __DIR__ . '/src/Tutorial/Controller/T1Controller.php',
    'TutorialTest\Framework\TestCase'        => __DIR__ . '/tests/Tutorial/Framework/TestCase.php',
    'TutorialTest\SampleTest'                => __DIR__ . '/tests/Tutorial/SampleTest.php',
);
