<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Abc\Module'                        => __DIR__ . '/Module.php',
    'Abc\Controller\SkeletonController' => __DIR__ . '/src/Abc/Controller/SkeletonController.php',
    'AbcTest\Framework\TestCase'        => __DIR__ . '/tests/Abc/Framework/TestCase.php',
    'AbcTest\SampleTest'                => __DIR__ . '/tests/Abc/SampleTest.php',
);
